# Generated by Django 4.2.1 on 2023-06-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetpad', '0005_alter_addexpense_info_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
