# Generated by Django 4.2.1 on 2023-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetpad', '0007_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addexpense_info',
            old_name='Date',
            new_name='due_date',
        ),
        migrations.AlterField(
            model_name='addexpense_info',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
