# Generated by Django 4.2.1 on 2023-06-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetpad', '0008_rename_date_addexpense_info_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addexpense_info',
            old_name='Category',
            new_name='category',
        ),
    ]
