# Generated by Django 4.2.1 on 2023-06-12 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgetpad', '0010_alter_addexpense_info_add_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='addexpense_info',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='addexpense_info',
            name='expense_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
