# Generated by Django 4.2.1 on 2023-06-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetpad', '0011_addexpense_info_date_addexpense_info_expense_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense_info',
            name='add_expense',
            field=models.CharField(max_length=15),
        ),
    ]
